version: "3"

services:
  play-server:
    build: .
    container_name: play-server
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 3000
